### ISSUE TITLE
Unicode commit logs from hg repositories get broken

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rolly32/rolly#18]
```
My old hg project log are in Chinese:

    https://code.google.com/p/zhmakeindex/source/list

But in the new project

    https://github.com/Leo-Liu/zhmakeindex/commits/master

all the Chinese characters are ??? in the log.
```

Original issue reported on code.google.com by `LeoLiu....@gmail.com` on 13 Mar 2015 at 8:57

**Comment by rolly32** [comment]
Same problem here! All mercurial commit messages shows ???? characters. 

Any one try to switch the repository type to git, and then make the export has 
workaround?

in time, my project: 
https://code.google.com/p/laemcasa/
Exported to:
https://github.com/bpvelloso/laemcasa
Original comment by bpvell...@gmail.com on 17 Mar 2015 at 4:04

**Comment by rolly32** [comment]
Same problem here! All mercurial commit messages shows ???? characters. 

Any one try to switch the repository type to git, and then make the export has 
workaround?

in time, my project: 
https://code.google.com/p/laemcasa/
Exported to:
https://github.com/bpvelloso/laemcasa
Original comment by bpvell...@gmail.com on 17 Mar 2015 at 4:04

**Comment by rolly32** [comment]
My old hg project log are in Chinese:

```
https://code.google.com/p/zhmakeindex/source/list
```

But in the new project

```
https://github.com/Leo-Liu/zhmakeindex/commits/master
```

all the Chinese characters are ??? in the log.
Original issue reported on code.google.com by LeoLiu....@gmail.com on 13 Mar 2015 at 8:57
